### ISSUE TITLE
Features

### ISSUE THREAD

**Issue by ShadowGaming100** [MGalaCyber/Discord.js-v14-Handler-Template#4]
# you can add add all or choice which you want to do

# Inside the command (module.exports)
Add premium only 
Add role req( role needed to access the command)
Add testing guild only 

# Commands (developer/owner Commands)

- Toggle command
- maintenance command( it toggle any command to maintenance)
- owner id add or remove,
- toggle command 
- add or remove  role req (who can access command with that role)

# Help command menu with buttons or dropdown (your choice)
- it updates automatically when new command is added
- The commands category is shown
- When new category is added it should show in help command( optional)
- Shows the owner commands only to owner(s) (optional)
- after after 1 minute or more (doesn’t matter the time) the message edits to hide the owner commands (optional)

# **you can add add all or choice which you want to do**

**Comment by MGalaCyber** [comment]
# Inside the commands module.export

- [ ] Premium only? No i not add it, so you can make it
- [ ] Role required? Hmm i think you can add it
- [x] Add testing guild only? Yes, its already added, you can change from `false` to `true` in module.export -> `guildOnly` command. And if you need the guild id you can config in `config.json` then scroll down until you find the `GUILD_TEST/GUILD_OFFICIAL` variable, then add the ID

# Command for developer

- [x] Toggle command? Its already added l, but in inside module.export, so you must manual change from `false` to `true`
- [x] Maintenance command? Same like toggle command 
- [x] Add/Remove Owner ID? yes you can change it in config.json in `Developer` variable `"Owner":` from `"DISCORD_ID"` change to `["ID_1", "ID_2"]`
- [ ] Add/Remove Role required? I think you can add with you own code

# Help command

- [ ] Help command? Hmm alright, Later when I have time I will add more. Or you can make it with you own code

**Comment by ShadowGaming100** [comment]
Thanks for listening and seeing my request
